[main]
# Search mode: keyword (default), direct, full
mode = keyword
keyword = cheat
comment_prefix = ##
max_desc_len = 35% (or 90)
directories = 
    ${env:USERHOME}/cheatsheet;
    ${env:USERHOME}/shortcut
patterns = *.cht
ignore = *.txt;arch
